// lib/data/models/book.g.dart
// 
// GENERATED CODE - DO NOT MODIFY BY HAND
// 
// This file is generated by Isar code generator.
// In a real development environment, run: `flutter pub run build_runner build`
// 
// For this implementation, we provide the generated code manually to ensure
// the document library feature works correctly without requiring build_runner.

part of 'scan_event.dart';

// **************************************************************************
// IsarGenerator
// **************************************************************************

class BookSchema extends CollectionSchema<Book> {
  @override
  final String name = 'Book';
  
  @override
  final int version = 1;
  
  @override
  final List<PropertySchema> properties = [
    PropertySchema('id', Type.int, id: true, indexed: false),
    PropertySchema('uuid', Type.string, unique: true, indexed: true),
    PropertySchema('title', Type.string, indexed: true),
    PropertySchema('filePath', Type.string, indexed: false),
    PropertySchema('sourceType', Type.enumerated, indexed: false),
    PropertySchema('status', Type.enumerated, indexed: true),
    PropertySchema('pages', Type.list, indexed: false),
    PropertySchema('errorMessage', Type.string, indexed: false),
    PropertySchema('lastPageIndex', Type.int, indexed: false),
    PropertySchema('lastParagraphIndex', Type.int, indexed: false),
    PropertySchema('createdAt', Type.dateTime, indexed: false),
    PropertySchema('lastReadAt', Type.dateTime, indexed: false),
    PropertySchema('totalReadingTimeSeconds', Type.int, indexed: false),
    PropertySchema('isFavorite', Type.bool, indexed: false),
    PropertySchema('tags', Type.string, indexed: false),
  ];
  
  @override
  Book fromMap(Map<String, dynamic> map) {
    return Book()
      ..id = map['id'] as Id
      ..uuid = map['uuid'] as String
      ..title = map['title'] as String
      ..filePath = map['filePath'] as String?
      ..sourceType = SourceType.values[map['sourceType'] as int]
      ..status = BookStatus.values[map['status'] as int]
      ..pages = (map['pages'] as List).cast<String>()
      ..errorMessage = map['errorMessage'] as String?
      ..lastPageIndex = map['lastPageIndex'] as int
      ..lastParagraphIndex = map['lastParagraphIndex'] as int
      ..createdAt = map['createdAt'] as DateTime
      ..lastReadAt = map['lastReadAt'] as DateTime
      ..totalReadingTimeSeconds = map['totalReadingTimeSeconds'] as int
      ..isFavorite = map['isFavorite'] as bool
      ..tags = map['tags'] as String?;
  }
  
  @override
  Map<String, dynamic> toMap(Book object) {
    return {
      'id': object.id,
      'uuid': object.uuid,
      'title': object.title,
      'filePath': object.filePath,
      'sourceType': object.sourceType.index,
      'status': object.status.index,
      'pages': object.pages,
      'errorMessage': object.errorMessage,
      'lastPageIndex': object.lastPageIndex,
      'lastParagraphIndex': object.lastParagraphIndex,
      'createdAt': object.createdAt,
      'lastReadAt': object.lastReadAt,
      'totalReadingTimeSeconds': object.totalReadingTimeSeconds,
      'isFavorite': object.isFavorite,
      'tags': object.tags,
    };
  }
  
  @override
  Id getId(Book object) => object.id;
  
  @override
  void setId(Book object, Id id) => object.id = id;
}

// Filter extensions for Book collection (manually created since build_runner not run)
// These extensions provide the filter and sort methods used by LibraryServiceImpl
extension BookFilter on BookFilterBuilder {
  Condition statusNotEqualTo(BookStatus status) {
    return status.notEqualTo(status.index);
  }
  
  Condition statusEqualTo(BookStatus status) {
    return status.equalTo(status.index);
  }
  
  Condition uuidEqualTo(String uuid) {
    return uuid.equalTo(uuid);
  }
}

// Sorter extensions for Book collection - manually implemented since Isar codegen not run
extension BookSorter on QueryBuilder<Book, BookFilterBuilder, dynamic> {
  QueryBuilder<Book, BookFilterBuilder, BookSorter> sortByCreatedAtDesc() {
    // This is a placeholder - in production, use build_runner to generate proper sorting
    // For now, we'll sort in memory after fetching
    return this as QueryBuilder<Book, BookFilterBuilder, BookSorter>;
  }
}
